apiVersion: v1
kind: Service
metadata:
  name: k8s-resource-monitor
  namespace: k8s-resource-monitor
spec:
  selector:
    app: k8s-resource-monitor
  ports:
  - name: http
    port: 80
    targetPort: 8000
  type: ClusterIP
